name: Cleanup Old Workflow Runs and Releases

on:
  schedule:
    - cron: "30 4 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 6

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          repo: ${{ github.repository }}
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
